---
- name: Configure UFW firewall
  hosts: all
  become: yes

  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present
      when: ansible_os_family == "Debian"

    - name: Allow SSH (22/tcp)
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Allow HTTP (80/tcp)
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Allow HTTPS (443/tcp)
      ufw:
        rule: allow
        port: "443"
        proto: tcp

    - name: Allow custom port (4000/tcp)
      ufw:
        rule: allow
        port: "4000"
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
        policy: allow
