---
- name: Install DSpace Prerequisites
  hosts: all
  become: yes

  pre_tasks:
    - name: Check if running in Docker container
      stat:
        path: /.dockerenv
      register: dockerenv_check

    - name: Check for Docker in cgroup (alternative detection)
      shell: cat /proc/1/cgroup | grep -q docker
      register: cgroup_docker_check
      failed_when: false
      changed_when: false

    - name: Set Docker detection fact
      set_fact:
        is_docker: "{{ dockerenv_check.stat.exists or cgroup_docker_check.rc == 0 }}"

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install basic packages
      apt:
        name:
          - software-properties-common
          - ca-certificates
          - curl
          - wget
          - gnupg
          - lsb-release
          - net-tools
          - unzip
          - bzip2
          - xz-utils
        state: present

    - name: Install optional interactive packages (skip in CI/Docker)
      apt:
        name:
          - vim
          - htop
          - emacs-nox
          - links
        state: present
      when: lookup('env', 'CI') != 'true'
      ignore_errors: yes

    - name: Set timezone
      timezone:
        name: "{{ timezone }}"

    - name: Generate locale
      locale_gen:
        name: "{{ locale }}"
        state: present

    - name: Set default locale
      command: update-locale LANG={{ locale }}
      changed_when: false

  tasks:
    - name: Setup swap (skip in Docker)
      include_role:
        name: swap
      when: not is_docker

  roles:
    - java
    - postgresql
    - nginx
    - tomcat
    - solr
    - certbot

- name: Import DSpace Backend Installation tasks
  import_playbook: install-dspace.yml

- name: Import DSpace Frontend Installation tasks
  import_playbook: install-frontend.yml

- name: Import Firewall tasks
  import_playbook: firewall.yml
    
